
# path to too binaries
TOOL_ROOT_FSPATH=$(GOPATH)/bin

# ADD all tools here !!!

TOOL_DUMMY_BIN_NAME=bs-dummy
TOOL_DUMMY_BIN_FSPATH=${TOOL_ROOT_FSPATH}/${TOOL_DUMMY_BIN_NAME}

TOOL_LANG_BIN_NAME=bs-lang
TOOL_LANG_BIN_FSPATH=${TOOL_ROOT_FSPATH}/${TOOL_LANG_BIN_NAME}

TOOL_PROTOFIG_BIN_NAME=bs-protofig
TOOL_PROTOFIG_BIN_FSPATH=${TOOL_ROOT_FSPATH}/${TOOL_PROTOFIG_BIN_NAME}

TOOL_PROTOC_GEN_CONFIGDEF_BIN_NAME=protoc-gen-configdef
TOOL_PROTOC_GEN_CONFIGDEF_BIN_FSPATH=${TOOL_ROOT_FSPATH}/${TOOL_PROTOC_GEN_CONFIGDEF_BIN_NAME}

TOOL_PROTODB_BIN_NAME=bs-protodb
TOOL_PROTODB_BIN_FSPATH=${TOOL_ROOT_FSPATH}/${TOOL_PROTODB_BIN_NAME}


tool-print:
	@echo
	@echo -- TOOL Print --
	@echo
	@echo TOOL_ROOT_FSPATH: 							$(TOOL_ROOT_FSPATH)
	@echo
	@echo TOOL_DUMMY_BIN_NAME: 							$(TOOL_DUMMY_BIN_NAME)
	@echo TOOL_DUMMY_BIN_FSPATH: 						$(TOOL_DUMMY_BIN_FSPATH)
	@echo
	@echo TOOL_LANG_BIN_NAME: 							$(TOOL_LANG_BIN_NAME)
	@echo TOOL_LANG_BIN_FSPATH: 						$(TOOL_LANG_BIN_FSPATH)
	@echo
	@echo TOOL_PROTOC_GEN_CONFIGDEF_BIN_NAME: 			$(TOOL_PROTOFIG_BIN_NAME)
	@echo TOOL_PROTOC_GEN_CONFIGDEF_BIN_FSPATH: 		$(TOOL_PROTOFIG_BIN_FSPATH)
	@echo
	@echo TOOL_PROTOFIG_BIN_NAME: 						$(TOOL_PROTOFIG_BIN_NAME)
	@echo TOOL_PROTOFIG_BIN_FSPATH: 					$(TOOL_PROTOFIG_BIN_FSPATH)
	@echo
	@echo TOOL_PROTODB_BIN_NAME: 						$(TOOL_PROTODB_BIN_NAME)
	@echo TOOL_PROTODB_BIN_FSPATH: 						$(TOOL_PROTODB_BIN_FSPATH)
	@echo
	@echo -- TOOL Print : end --
	@echo


