
# path to too binaries
TOOL_ROOT_FSPATH=$(GOPATH)/bin

# ADD all tools here !!!

TOOL_DUMMY_BIN_NAME=bs-dummy
TOOL_DUMMY_BIN_FSPATH=${TOOL_ROOT_FSPATH}/${TOOL_DUMMY_BIN_NAME}

TOOL_LANG_BIN_NAME=bs-lang
TOOL_LANG_BIN_FSPATH=${TOOL_ROOT_FSPATH}/${TOOL_LANG_BIN_NAME}

TOOL_PROTOFIG_BIN_NAME=bs-protofig
TOOL_PROTOFIG_BIN_FSPATH=${TOOL_ROOT_FSPATH}/${TOOL_PROTOFIG_BIN_NAME}


tool-print:
	@echo
	@echo -- TOOL --
	@echo TOOL_ROOT_FSPATH: 				$(TOOL_ROOT_FSPATH)

	@echo TOOL_DUMMY_BIN_NAME: 				$(TOOL_DUMMY_BIN_NAME)
	@echo TOOL_DUMMY_BIN_FSPATH: 			$(TOOL_DUMMY_BIN_FSPATH)

	@echo TOOL_LANG_BIN_NAME: 				$(TOOL_LANG_BIN_NAME)
	@echo TOOL_LANG_BIN_FSPATH: 			$(TOOL_LANG_BIN_FSPATH)

	@echo TOOL_PROTOFIG_BIN_NAME: 			$(TOOL_PROTOFIG_BIN_NAME)
	@echo TOOL_PROTOFIG_BIN_FSPATH: 		$(TOOL_PROTOFIG_BIN_FSPATH)
	@echo -- TOOL: end --
	@echo

