kind: pipeline
type: docker
name: default
   
steps:

# Notify Telegram that tests are passed
  - name: telgram_notify
    image: appleboy/drone-telegram
    when:
      status:
        - success
        - failure
    settings:
      # The secrets below can be entered from the Drone UI for this repo
      token:
        from_secret: telegram-token
      to:
        from_secret: telegram-to
      format: markdown
      message: >
        {{#success build.status}}
        ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.
        📝 Commit by {{commit.author}} on `{{commit.branch}}`:
        ```
        {{commit.message}}
        ```
        🌐 {{ build.link }}
        {{else}}
        ❌ Build #{{build.number}} of `{{repo.name}}` failed.
        📝 Commit by {{commit.author}} on `{{commit.branch}}`:
        ```
        {{commit.message}}
        ```
        🌐 {{ build.link }}
        {{/success}}

- name: test-flutter
  image: cirrusci/flutter:stable
  commands:
    - sudo chown -R cirrus:cirrus .
    - flutter doctor
    - flutter test

- name: test-make
  image: alpine
  commands:
  - echo hello
  - echo world
  - make this-build
