include ../../boilerplate/core/gitr.mk
include ../../boilerplate/core/help.mk

## Run the example (only after installing protofig)
this-run-example:
	bs-protofig -f $(PWD)/config.default-winwisely.json -u winwiselyxx -o output
